### ISSUE TITLE
status 404

### ISSUE THREAD

**Issue by keturn** [MikeSafonov/jenkins-linter-idea-plugin#59]
When I use the validate action, the tool window says "HTTP response status code: 404."

I have configured the linter's settings and when I use the "check connection" button it reports success.

I do not see any indication of which URL it requested to receive the 404 response.

**Comment by keturn** [comment]
I think it likely because this is using an absolute path: https://github.com/MikeSafonov/jenkins-linter-idea-plugin/blob/48db173270a34315ade85648f37036f6eb992dd0/src/main/kotlin/com/github/mikesafonov/jenkins/linter/api/JenkinsServerImpl.kt#L56

Our Jenkins instance is not served from the root path `/`, so it will be important for this URL to be built relative to the one entered in the settings.

**Comment by hjinbi** [comment]
Is there any solution?

**Comment by MikeSafonov** [comment]
Hello. Thanks for the report.
Please try 0.5.0 version.

**Comment by Sani33** [comment]
Works for me.

**Comment by keturn** [comment]
Thank you for the fix!
